config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "home/index", as: :home
  devise_for :users, controllers: {registrations: "registrations"}
  as :user do
    # after editing the profile, stay on the edit profile page as user_root
    get "users/profile", to: "devise/registrations#edit", as: :user_root
  end

  # Defines the root path route ("/")
  root "home#index"

  # bottles and stores aren't full CRUD - maybe not resources
  resources :olcc_bottles
  resources :olcc_stores

  get "tasks/daily"
end

app/views/layouts/content/_bottles_index.html.erb
<!-- BEGIN Bottles Index (Authenticated) include -->
<div class="">
  <div class="mb-5">
    <h2>Bottles</h2>
    <%= form_with method: :get do |form| %>
      <%= form.label :query, "Search for bottle:" %>
      <%= form.text_field :query, value: @query %>
      <%= form.submit "Search" %>
    <% end %>
  </div>
  <% if @query %>
    <h3>Bottles in OLCC</h3>
  <% else %>
    <h3>List of My Bottles</h3>
  <% end %>
  <table class="table table-striped table-hover align-top mb-5 table-feature-comparison">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody class="table-striped table-group-divider align-middle">
    <% @olcc_bottles.each_with_index do |bottle, index| %>
      <tr>
        <td><%= link_to bottle.name, bottle %></td>
        <td><%= number_to_currency(bottle.bottle_price) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<!-- END Bottles Index (Authenticated) include -->

app/views/layouts/content/_bottles_show.html.erb
<!-- BEGIN Bottles Show (Authenticated) include -->
<div class="">
  <div class="mb-5">
    <div class="mb-3">
      <h2 class="d-inline"><%= @bottle.name %></h2>
      <% user_follows = current_user.is_following?(@bottle) %>
      <%= form_with(model: @bottle, method: "patch", class: "d-inline") do |form| %>
        <% if user_follows %>
          <%= form.hidden_field :follow, value: "false" %>
          <i class="bi bi-heart-fill fs-5 text-danger"></i>
          <%= form.button "Unfollow" %>
        <% else %>
          <%= form.hidden_field :follow, value: "true" %>
          <i class="bi bi-heart fs-5 text-danger"></i>
          <%= form.button "Follow" %>
        <% end %>
      <% end %>
    </div>
    <div class="text-secondary">
      <div class="row">
        <div class="col-3 col-md-2 text-end text-nowrap">
          <p class="mb-2"><i class="bi bi-diagram-3-fill"></i> Category</p>
        </div>
        <div class="col-auto">
          <p class="mb-0"><%= @bottle.category.titleize %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-3 col-md-2 text-end text-nowrap">
          <p class="mb-2"><i class="bi bi-tag-fill"></i> Price</p>
        </div>
        <div class="col-auto">
          <p class="mb-0 fst-italic"><%= number_to_currency(@bottle.bottle_price) %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-3 col-md-2 text-end text-nowrap">
          <p class="mb-2"><i class="bi bi-arrows-fullscreen"></i> Size</p>
        </div>
        <div class="col-auto">
          <p class="mb-0 fst-italic"><%= @bottle.size %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-3 col-md-2 text-end text-nowrap">
          <p class="mb-2"><i class="bi bi-radioactive"></i> Proof</p>
        </div>
        <div class="col-auto">
          <p class="mb-0 fst-italic"><%= @bottle.proof %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-3 col-md-2 text-end text-nowrap">
          <p class="mb-2"><i class="bi bi-hourglass-split"></i> Age</p>
        </div>
        <div class="col-auto">
          <p class="mb-0 fst-italic"><%= @bottle.age.empty? ? "NAS" : @bottle.age %></p>
        </div>
      </div>
    </div>
  </div>
  <% num_stores = @inventory.size %>
  <% if num_stores == 0 %>
    <h3>It is NOT available at any of your stores.</h3>
  <% else %>
    <h3>Available at the following <%= pluralize(num_stores, 'store') %>:</h3>
    <table class="table table-striped table-hover align-top mb-5 table-feature-comparison">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Address</th>
          <th scope="col">Hours</th>
          <th scope="col" class="text-end">Quantity</th>
        </tr>
      </thead>
      <tbody class="table-striped table-group-divider align-middle">
      <% @inventory.each_with_index do |inv, index| %>
        <tr>
          <td><%= link_to inv.olcc_store.name, inv.olcc_store %></td>
          <td><address class="mb-0"><%= inv.olcc_store.address %></address></td>
          <td class="fst-italic"><%= inv.olcc_store.store_hours %></td>
          <td class="text-end pe-4"><%= inv.quantity %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>
</div>
<!-- END Bottles Show (Authenticated) include -->

app/views/layouts/content/_home_anonymous.html.erb
<!-- BEGIN Home (Anonymous) include -->
<div class="p-4">
  <!-- BEGIN Become a Hound include -->
  <h3>Become a Hound</h3>
  <p>Click <em>Create an Account</em> below to sign up and become a <em>Booze Hound</em>.</p>
  <p>If you're already a member, sign in below.</p>
  <ul class="nav list-group">
    <% if false %>
      <li class="list-group-item"><i class="fa-solid fa-user-plus me-2" style="width: 20px;"></i><%= link_to "Create an Account", new_user_registration_path, class: "nav-link d-inline" %></li>
    <% end %>
    <li class="list-group-item"><i class="fa-solid fa-right-to-bracket me-2" style="width: 20px"></i><%= link_to "Sign In", new_user_session_path, class: "nav-link d-inline" %></li>
  </ul>
  <!-- END Become a Hound include -->
</div>
<div class="p-4">
  <div class="row">
    <div class="col-lg-8">
      <h2>What is Booze Hound?</h2>
      <p>Are you an Oregonian who has used the Oregon Liquor &amp; Cannabis Commission's (OLCC) <em>Oregon Liquor Search</em> site but you've been frustrated with the experience? Welcome to <em>Booze Hound!</em></p>
      <p><em>Booze Hound</em> is an improved user experience for Oregonians who use the Oregon Liquor &amp; Cannabis Commission's (OLCC) <em>Oregon Liquor Search</em> site.</p>
    </div>
    <div class="col-lg-4">
      <p class="placeholder-wave">
        <span class="placeholder"><img src="" width="266px" height="200px" title="TBD: screenshot" /></span>
      </p>
    </div>
  </div>
  <p>The additional functionality and improved user interface of Booze Hound allows users to:</p>
  <ul class="list-group list-group-flush mb-5">
    <li class="list-group-item"><i class="bi bi-plus-circle-fill me-3 text-primary" style="width: 20px;"></i>Create an account for a customized experience</li>
    <li class="list-group-item"><i class="bi bi-plus-circle-fill me-3 text-primary" style="width: 20px;"></i>Follow one or more stores for updates to stock</li>
    <li class="list-group-item"><i class="bi bi-plus-circle-fill me-3 text-primary" style="width: 20px;"></i>Follow one or more categories of liquor for updates to stock</li>
    <li class="list-group-item fst-italic"><i class="bi bi-plus-circle-fill me-3 text-primary" style="width: 20px;"></i>...and more!</li>
  </ul>
  <h3>Feature Comparison</h3>
  <table class="table table-striped table-hover align-top mb-5 table-feature-comparison">
    <thead>
      <tr>
        <th scope="col" class="">Feature</th>
        <th scope="col" class="fs-5 text-center">Booze Hound</th>
        <th scope="col" class="text-secondary fw-normal fs-5 text-center">Oregon Liquor Search</th>
      </tr>
    </thead>
    <tbody class="table-striped table-group-divider align-middle">
      <tr>
        <td class="fst-italic">Personalized settings that persist between sessions</td>
        <td class="text-center"><span class="badge rounded-pill text-bg-success p-1 fs-5"><i class="bi bi-check-circle-fill"></i></span></td>
        <td class="text-center"><span class="badge rounded-pill text-bg-danger p-1 fs-5"><i class="bi bi-x-circle-fill"></i></span></td>
      </tr>
      <tr>
        <td class="fst-italic">Follow stores for inventory updates</td>
        <td class="text-center"><span class="badge rounded-pill text-bg-success p-1 fs-5"><i class="bi bi-check-circle-fill"></i></span></td>
        <td class="text-center"><span class="badge rounded-pill text-bg-danger p-1 fs-5"><i class="bi bi-x-circle-fill"></i></span></td>
      </tr>
      <tr>
        <td class="fst-italic">Follow liquor categories for product updates</td>
        <td class="text-center"><span class="badge rounded-pill text-bg-success p-1 fs-5"><i class="bi bi-check-circle-fill"></i></span></td>
        <td class="text-center"><span class="badge rounded-pill text-bg-danger p-1 fs-5"><i class="bi bi-x-circle-fill"></i></span></td>
      </tr>
      <tr>
        <td class="fst-italic">Follow individual products for availability updates</td>
        <td class="text-center"><span class="badge rounded-pill text-bg-success p-1 fs-5"><i class="bi bi-check-circle-fill"></i></span></td>
        <td class="text-center"><span class="badge rounded-pill text-bg-danger p-1 fs-5"><i class="bi bi-x-circle-fill"></i></span></td>
      </tr>
      <tr>
        <td class="fst-italic">Responsive, mobile-first user interface</td>
        <td class="text-center"><span class="badge rounded-pill text-bg-success p-1 fs-5"><i class="bi bi-check-circle-fill"></i></span></td>
        <td class="text-center"><span class="badge rounded-pill text-bg-danger p-1 fs-5"><i class="bi bi-x-circle-fill"></i></span></td>
      </tr>
    </tbody>
  </table>
  <div class="alert alert-primary fst-italic" role="alert">
    <p class="m-0 p-0">Create a <em>Booze Hound</em> account today or sign in to begin sniffing out your favorite spirits!</p>
  </div>
</div>
<!-- END Home (Anonymous) include -->

app/views/layouts/content/_home_authenticated.html.erb
<!-- BEGIN Home (Authenticated) include -->
<div class="">
  <%= yield %>
  <h2>Recent Events:</h2>
  <% if @events.none? %>
    <h3>No news is boring</h3>
  <% else %>
    <table class="table table-striped table-hover align-top mb-3 table-feature-comparison">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Bottle</th>
          <th scope="col">Info</th>
        </tr>
      </thead>
      <tbody class="table-striped table-group-divider align-middle">
      <% @events.each_with_index do |event, index| %>
        <tr>
          <td><%= format_date(event) %></td>
          <td><%= link_to event.olcc_bottle.name, event.olcc_bottle %></td>
          <td><%= show_event(event) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <%end %>
  <% if @prev_page %>
    <%= link_to home_path(page: @prev_page), class: "my-2, link-underline link-underline-opacity-0" do %>
      <i class="bi bi-arrow-left-square me-1"></i>Previous
    <% end %>
  <% end %>
  <% if @next_page and @prev_page %>
    <span class="mx-2"></span>
  <% end %>
  <% if @next_page %>
    <%= link_to home_path(page: @next_page), class: "my-2, link-underline link-underline-opacity-0" do %>
      Next<i class="bi bi-arrow-right-square ms-1"></i>
    <% end %>
  <% end %>
</div>
<!-- END Home (Authenticated) include -->

app/views/layouts/content/_stores_index.html.erb
<!-- BEGIN Stores Index (Authenticated) include -->
<div class="">
  <div class="mb-5">
    <h2>Stores</h2>
    <%= form_with method: :get do |form| %>
      <%= form.label :query, "Search for stores:" %>
      <%= form.text_field :query, value: @query %>
      <%= form.submit "Search" %>
    <% end %>
  </div>
  <% if @query %>
    <h3>OLCC Stores</h3>
  <% else %>
    <h3>List of My OLCC Stores</h3>
  <% end %>
  <table class="table table-striped table-hover align-top mb-5 table-feature-comparison">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Address</th>
        <th scope="col">Store Hours</th>
      </tr>
    </thead>
    <tbody class="table-striped table-group-divider align-middle">
    <% @olcc_stores.each_with_index do |store, index| %>
      <tr>
          <td><%= link_to store.name, store %></td>
          <td><%= store.address %></td>
          <td><%= store.store_hours %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<!-- END Stores Index (Authenticated) include -->

app/views/layouts/content/_stores_show.html.erb
<!-- BEGIN Stores Show (Authenticated) include -->
<div class="">
  <div class="mb-5">
    <div class="mb-3">
      <h2 class="d-inline"><%= @store.name %></h2>
      <% user_favorite = current_user.is_favorite_store?(@store) %>
      <%= form_with(model: @store, method: "patch", class: "d-inline") do |form| %>
        <% if user_favorite %>
          <%= form.hidden_field :follow, value: "false" %>
          <i class="bi bi-heart-fill fs-5 text-danger"></i>
          <%= form.button "Unfollow" %>
        <% else %>
          <%= form.hidden_field :follow, value: "true" %>
          <i class="bi bi-heart fs-5 text-danger"></i>
          <%= form.button "Follow" %>
        <% end %>
      <% end %>
    </div>
    <div class="text-secondary">
      <div class="row">
        <div class="col-3 col-md-2 text-end text-nowrap">
          <p class="mb-2"><i class="bi bi-geo-alt-fill"></i> Address</p>
        </div>
        <div class="col-auto">
          <address class="mb-0"><%= @store.address %></address>
        </div>
      </div>
      <div class="row">
        <div class="col-3 col-md-2 text-end text-nowrap">
          <p class="mb-2"><i class="bi bi-clock-fill"></i> Hours</p>
        </div>
        <div class="col-auto">
          <p class="mb-0 fst-italic"><%= @store.store_hours %></p>
        </div>
      </div>
    </div>
  </div>
  <h3>Store Inventory</h3>
  <table class="table table-striped table-hover align-top mb-5 table-feature-comparison">
    <thead>
      <tr>
        <th scope="col">Item Code</th>
        <th scope="col">Name</th>
        <th scope="col" class="text-end">Price</th>
        <th scope="col" class="text-end">Quantity</th>
      </tr>
    </thead>
    <tbody class="table-striped table-group-divider align-middle">
    <% @inventory.each_with_index do |inv, index| %>
      <tr>
        <td><%= inv.olcc_bottle.new_item_code %></td>
        <td><%= link_to inv.olcc_bottle.name, inv.olcc_bottle %></td>
        <td class="text-end"><%= number_to_currency(inv.olcc_bottle.bottle_price) %></td>
        <td class="text-end pe-4"><%= inv.quantity %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<!-- END Stores Show (Authenticated) include -->

app/views/layouts/content/_user_show.html.erb
<!-- BEGIN User Show include -->
<div class="mb-5">    
  <h2>User Profile for <span class="fst-italic fw-normal text-primary"><%= @user.first_name + " " + @user.last_name %></span></h2>
  <div class="row mb-3">
    <div class="col">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#{user_root_profile}">View Profile</a>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path(current_user), :class => 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <form class="needs-validation" novalidate="">
        <div class="row">
          <div class="col-sm-6 mb-5">
            <label for="firstName" class="form-label fw-bold">First name</label>
            <input type="text" class="form-control-plaintext" id="first_name" placeholder="" value="<%= @user.first_name %>" required>
            <div class="invalid-feedback">Valid first name is required.</div>
          </div>
          <div class="col-sm-6 mb-5">
            <label for="lastName" class="form-label fw-bold">Last name</label>
            <input type="text" class="form-control-plaintext" id="last_name" placeholder="" value="<%= @user.last_name %>" required>
            <div class="invalid-feedback">Valid last name is required.</div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 mb-5">
            <label for="email" class="form-label fw-bold">Email address</label>
            <p class="fst-italic small">Your email address is used for notifications and password reset links.</p>
            <input type="email" class="form-control-plaintext" id="email" placeholder="you@example.com" value="<%= @user.email %>" required>
            <div class="invalid-feedback">Please enter a valid email address.</div>
          </div>
          <div class="col-sm-6"></div>
        </div>
        <div class="row">
          <div class="col-sm-6 mb-5">
            <label for="username" class="form-label fw-bold">Username</label>
            <p class="fst-italic small">This is your display name as it appears to other users.</p>
            <div class="input-group has-validation">
              <input type="text" class="form-control-plaintext" id="username" placeholder="Username" value="<%= @user.username %>" required>
              <div class="invalid-feedback">Your username is required.</div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12 mb-5">
            <label class="form-label fw-bold">Followed categories</label>
            <p class="fst-italic small">These are the bottle categories you follow.</p>
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="category-1" disabled>
              <label class="form-check-label" for="category-1">Domestic Whiskey</label>
            </div>
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="category-2" disabled checked>
              <label class="form-check-label" for="category-2">Rum</label>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12 mb-5">
            <label class="form-label fw-bold">Terms and conditions acknowledgements</label>
            <p class="fst-italic small">These fields are read-only.</p>
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="ack-age" checked disabled readonly>
              <label class="form-check-label fst-italic" for="ack-age">I affirm that I am at least 21 years of age.</label>
            </div>
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="ack-resident" checked disabled readonly>
              <label class="form-check-label fst-italic" for="ack-resident">I affirm that I am a legal resident of the state of Oregon.</label>
            </div>
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="ack-tc" checked disabled readonly>
              <label class="form-check-label fst-italic" for="ack-tc">I affirm that I have agreed to the terms and conditions of this site.</label>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- END User Show include -->