config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "home/index", as: :home
  devise_for :users, controllers: {registrations: "registrations"}
  as :user do
    # after editing the profile, stay on the edit profile page as user_root
    get "users/profile", to: "devise/registrations#edit", as: :user_root
  end

  # Defines the root path route ("/")
  root "home#index"

  # bottles and stores aren't full CRUD - maybe not resources
  resources :olcc_bottles
  resources :olcc_stores

  get "tasks/daily"
end

app/models/olcc_bottle.rb
class OlccBottle < ApplicationRecord
  self.primary_key = "new_item_code"
  has_many :bottle_events, foreign_key: "new_item_code"
  has_and_belongs_to_many :followers, class_name: "User", foreign_key: "new_item_code"

  # description is ALL CAPS from OLCC. name is a more user-friendly
  # version - give it an initial mixed-case value based on description.
  before_create do
    self.name = description.titleize if name.blank?
    self.next_bottle_price = bottle_price if next_bottle_price.nil?
  end
  # and keep it in sync if the description changes
  before_update do
    sync_name_to_description

    if bottle_price_changed?
      # synchronize next_bottle price unless it changed too
      self.next_bottle_price = bottle_price unless next_bottle_price_changed?
    end
  end

  CATEGORIES = [
    "BRANDY / COGNAC",
    "CACHACA",
    "CORDIALS",
    "DOMESTIC WHISKEY",
    "GIN",
    "IRISH",
    "RUM",
    "TEQUILA",
    "VODKA"
  ].freeze
  enum category: CATEGORIES.index_by(&:to_s)

  def self.followed_bottles
    # order by category so each category will show up as a block together
    OlccBottle.where("followers_count > 0").order(:category)
  end

  def self.search(unsafe_query)
    safe_query = OlccBottle.sanitize_sql_like(unsafe_query)
    OlccBottle.where("name LIKE ?", "%" + safe_query + "%").order(:name)
  end

  # After adding the before_create hook, this might be obsolete
  def prettify_name(better_name = nil)
    if better_name
      self.name = better_name
    elsif name == description
      self.name = name.titleize
    end

    save
  end

  private

  def sync_name_to_description
    desc_change = changes_to_save[:description]
    if desc_change
      prev_desc = desc_change.first
      if name == prev_desc.titleize
        # the name is the default based on the previous description
        self.name = description.titleize
      end
    end
  end
end

app/controllers/olcc_bottles_controller.rb
class OlccBottlesController < ApplicationController
  # for now, all operations require login
  before_action :check_and_setup_user

  def index
    if params[:query]
      @olcc_bottles = OlccBottle.search(params[:query])
      @query = params[:query]
    else
      @olcc_bottles = UserBottlesQuery.call(current_user)
    end
    # might want two different views for my bottles vs. search bottles
    # with the option to start following bottles in search results
  end

  def show
    @bottle = OlccBottle.find(params[:id])
    @inventory = StoreQuery.call(@bottle, current_user.favorite_store_ids)
  end

  def update
    @bottle = OlccBottle.find(params[:id])
    if params[:olcc_bottle][:follow] == "true"
      UserFollowBottle.call(olcc_client, current_user, @bottle)
    else
      current_user.unfollow_bottle(@bottle)
    end

    redirect_to @bottle
  end

  def create
    new_item_code = clean_item_code_param(:new_item_code)
    category = params[:category]  # sanitize?
    unless new_item_code && category
      flash[:notice] = "An error occurred finding that bottle. Sorry."
      redirect_back(fallback_location: root_path)
      return
    end

    bottle = LoadBottle.call(olcc_client, category, new_item_code)
    if bottle
      # success - show it
      redirect_to bottle
    else
      # Could get the error_message from LoadBottle - maybe someday
      flash[:notice] = "An error occurred finding bottle #{new_item_code}. Sorry."
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def clean_item_code_param(key)
    val = "" && params[key].strip
    if /^\d+$/.match?(val)
      val
    end
  end
end

app/helpers/olcc_bottle_helper.rb
module OlccBottleHelper
  def category_select(form)
    labels_values = []
    OlccBottle::CATEGORIES.each do |cap_cat|
      labels_values << [cap_cat.titleize, cap_cat]
    end

    form.select :category, labels_values
  end
end

app/views/olcc_bottles/index.html.erb
<div class="row">
  <div class="col-lg-4 order-lg-2">
    <%= render 'layouts/sidebar/user_menu_authenticated' %>
  </div>
  <div class="col-lg-8 order-lg-1">
    <!-- BEGIN Main Body Content include -->
    <%= render 'layouts/content/bottles_index' %>
    <!-- END Main Body Content include -->
  </div>
</div>
<div class="mt-5 border border-1 p-3">
<h5><em>Warning: some hacky UI stuff below:</em></h5>
  <p><em>Hacky admin function I don't want to lose:</em></p>
  <p>Add a bottle based on the OLCC new item code:</p>
  <%= form_with url: olcc_bottles_path do |form| %>
    <div>
      <%= form.label :new_item_code %>
      <%= form.text_field :new_item_code %>
      <%= category_select(form) %>
    </div>
    <div>
      <%= form.submit "Search" %>
    </div>
  <% end %>
</div>

app/views/olcc_bottles/show.html.erb
<div class="row">
  <div class="col-lg-4 order-lg-2">
    <%= render 'layouts/sidebar/user_menu_authenticated' %>
  </div>
  <div class="col-lg-8 order-lg-1">
    <!-- BEGIN Main Body Content include -->
    <%= render 'layouts/content/bottles_show' %>
    <!-- END Main Body Content include -->
  </div>
</div>