config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "home/index", as: :home
  devise_for :users, controllers: {registrations: "registrations"}
  as :user do
    # after editing the profile, stay on the edit profile page as user_root
    get "users/profile", to: "devise/registrations#edit", as: :user_root
  end

  # Defines the root path route ("/")
  root "home#index"

  # bottles and stores aren't full CRUD - maybe not resources
  resources :olcc_bottles
  resources :olcc_stores

  get "tasks/daily"
end

app/views/layouts/components/_foot.html.erb
    <!-- BEGIN Foot include -->
    <!-- BEGIN Twitter Bootstrap include -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <!-- END Twitter Bootstrap include -->
    <!-- BEGIN jQuery and jQuery UI includes -->
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js" integrity="sha256-xLD7nhI62fcsEZK2/v8LsBcb4lG7dgULkuXoXB/j91c=" crossorigin="anonymous"></script>
    <!-- END jQuery and jQuery UI includes -->
    <!-- BEGIN FontAwesome 6 include -->
    <script src="https://kit.fontawesome.com/a744f5988e.js" crossorigin="anonymous"></script>
    <!-- END FontAwesome 6 include -->
    <!-- BEGIN Booze Hound include -->
    <%= javascript_include_tag '/js/main.js' %>
    <!-- END Booze Hound include -->
    <!-- END Foot include -->

app/views/layouts/components/_footer.html.erb
    <!-- BEGIN Footer include -->
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">Booze Hound</a>
        <span class="mb-3 mb-md-0 text-body-secondary">© <span id="footerCopyrightRange">2023</span> Booze Hound</span>
      </div>
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="nav-item"><a class="nav-link text-body-secondary" href="/">Home</a></li>
        <li class="nav-item"><a class="nav-link text-body-secondary" href="/find">Find</a></li>
        <li class="nav-item"><a class="nav-link text-body-secondary" href="/browse">Browse</a></li>
        <% if user_signed_in? %>
          <% @user_url = user_root_url %>
        <% else %>
          <% @user_url = "/users/sign_in" %>
        <% end %>
        <li class="nav-item"><a class="nav-link text-body-secondary" href="<%= @user_url %>">User</a></li>
        <li class="nav-item"><a class="nav-link text-body-secondary" href="/about">About</a></li>
      </ul>
    </footer>
    <!-- END Footer include -->

app/views/layouts/components/_head.html.erb
    <!-- BEGIN Head include -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <title>Booze Hound</title>
    <!-- BEGIN Bootstrap CSS include -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <!-- END Bootstrap CSS include -->
    <!-- BEGIN Bootstrap Icons CSS include -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <!-- END Bootstrap Icons CSS include -->
    <!-- BEGIN Booze Hound CSS include -->
    <!-- <link rel="stylesheet" href="styles/styles.css"> -->
    <!-- END Booze Hound CSS include -->
    <!-- END Head include -->

app/views/layouts/components/_header.html.erb
<!-- BEGIN Header include -->
<header class="my-4">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <div class="me-5">
        <a class="navbar-brand mb-2 mb-lg-0 text-decoration-none fs-1" href="/"><i class="fa-solid fa-dog"></i><i class="fa-solid fa-martini-glass fs-4 me-3"></i>Booze Hound</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 me-3 mb-lg-0">
          <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="/browse" role="button" data-bs-toggle="dropdown" aria-expanded="false">Find/Browse</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/find"><i class="fa-solid fa-magnifying-glass me-2" style="width: 20px;"></i>Find</a></li>
              <li><a class="dropdown-item" href="/olcc_bottles"><i class="fa-solid fa-bottle-droplet me-2" style="width: 20px;"></i>Bottles</a></li>
              <li><a class="dropdown-item" href="/olcc_stores"><i class="fa-solid fa-shop me-2" style="width: 20px;"></i>Stores</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="/user/1" role="button" data-bs-toggle="dropdown" aria-expanded="false">User</a>
            <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><span class="dropdown-item fst-italic bg-transparent"><%= current_user.email %></span></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="<%= user_root_url %>"><i class="fa-solid fa-user me-2" style="width: 20px;"></i>User Profile</a></li>
              <li><a class="dropdown-item" href="/olcc_bottles"><i class="fa-solid fa-whiskey-glass me-2" style="width: 20px;"></i>Favorite Bottles</a></li>
              <li><a class="dropdown-item" href="/olcc_stores"><i class="fa-solid fa-shop me-2" style="width: 20px;"></i>Favorite Stores</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="/users/sign_out" data-turbo-method=":delete"><i class="fa-solid fa-right-from-bracket me-2" style="width: 20px;"></i>Logout</a></li>
            <% else %>
              <% if false %>
                <li><a class="dropdown-item" href=<%= new_user_registration_path %>><i class="fa-solid fa-user-plus me-2 text-danger" style="width: 20px;"></i>Create an Account<i class="bi bi-unlock-fill ms-2"></i></a></li>
              <% end %>
              <li><a class="dropdown-item" href=<%= new_user_session_path %>><i class="fa-solid fa-right-to-bracket me-2 text-danger" style="width: 20px"></i>Sign In<i class="bi bi-unlock-fill ms-2"></i></a></li>
            <% end %>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="/about" role="button" data-bs-toggle="dropdown" aria-expanded="false">About</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/about/help"><i class="fa-solid fa-question me-2" style="width: 20px"></i>Help</a></li>
              <li><a class="dropdown-item" href="/about/updates"><i class="fa-solid fa-newspaper me-2" style="width: 20px"></i>Updates</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
<!-- END Header include -->